services:
    mysql:
        container_name: Tests
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            # пароль для root пользователя
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            # хосты, с которых можно подключаться к БД
            MYSQL_ROOT_HOST: '%'
            # имя БД, которую создает Sail
            MYSQL_DATABASE: '${DB_DATABASE}'
            # имя пользователя, под которым создает Sail
            MYSQL_USER: '${DB_USERNAME}'
            # пароль, под которым создает Sail
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            # позволять пустой пароль
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            # файловая система, где хранятся файлы БД
            - 'sail-mysql:/var/lib/mysql'
            # файл, который будет выполнен при запуске контейнера
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            # сеть, к которой подключается контейнер
            - sail
        healthcheck:
            # команда, которая будет выполнена, чтобы проверить, работает ли контейнер
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            # количество попыток, которые нужно сделать, чтобы убедиться, что контейнер не работает
            retries: 3
            # время, которое нужно ждать между попытками
            timeout: 5s
    phpmyadmin:
        networks:
            - sail
        image: phpmyadmin/phpmyadmin
        links:
          - mysql:mysql
        ports:
          - 8080:80
        environment:
          MYSQL_USERNAME: "${DB_USERNAME}"
          MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
          PMA_HOST: mysql

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: selenium/standalone-chromium
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
